### ISSUE TITLE
About initialization of hidden states in sentence-level ON-LSTM

### ISSUE THREAD

**Issue by awkrail** [hwang1996/SGN#1]
Hi, thank you for providing the source code of your paper. I am very interested in your paper.
I'd like to ask you a question about initializing hidden states in ON-LSTM.

From line 126 to 146 at `train.py`, the code initialize hidden states when starting a batch (L125~L127).
Then, the sentence-level ON-LSTM hidden state, namely `hidden`, is used for training (L146).
However, at next iteration, this `hidden` is used again after detaching, although it is not related to the next iteration.

I think that this `hidden` should be again initialized as zero vectors.
Could you tell me why you used the previous hidden state is used during training?

Thanks

```python
    hidden = model.init_hidden(args.batch_size)
    hidd = model.init_hidden(args.batch_size*19)
    hidd_cand = model.init_hidden(args.batch_size*4)
    batch = 0
    acc_list = []
    total_var = 0

    it = tqdm(range(len(train_dataloader)), desc="Epoch {}/{}".format(epoch, args.epochs), ncols=0)
    data_iter = iter(train_dataloader)
    for niter in it:
        input_ids, cand_ids, target = data_iter.next()
        if args.cuda:
            input_ids = input_ids.cuda()
            cand_ids = cand_ids.cuda()
            targets = target.cuda()

        hidden = repackage_hidden(hidden)
        hidd = repackage_hidden(hidd)
        hidd_cand = repackage_hidden(hidd_cand)
        optimizer.zero_grad()

        output, result_prob, hidden, rnn_hs, dropped_rnn_hs, cand_emb = model(input_ids, cand_ids, hidden, hidd, hidd_cand)
```

**Comment by hwang1996** [comment]
Hi, thanks for your suggestions. We follow the programming in the [original ON-LSTM codes](https://github.com/yikangshen/Ordered-Neurons/blob/46d63cde024802eaf1eb7cc896431329014dd869/main.py#L211), where they work at language modeling task and their training samples in each batch are part of the whole documents. 
In our setting, there is no specific reason for doing so. Since the hidden state has been detached, it would not affect the following training. You can also try initializing the hidden states in each batch, that should give similar results.

**Comment by awkrail** [comment]
Thanks!
